openapi: 3.0.0
info:
  title: '55415'
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /kgfkg:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    coord:
                      lon: -121.95
                      lat: 37.35
                    weather:
                      - id: 803
                        main: Clouds
                        description: broken clouds
                        icon: 04n
                    base: stations
                    main:
                      temp: 45.25
                      feels_like: 41.16
                      temp_min: 41
                      temp_max: 50
                      pressure: 1026
                      humidity: 75
                    visibility: 16093
                    wind:
                      speed: 2.57
                      deg: 36
                    clouds:
                      all: 75
                    dt: 1579415808
                    sys:
                      type: 1
                      id: 5845
                      country: US
                      sunrise: 1579360793
                      sunset: 1579396557
                    timezone: -28800
                    id: 0
                    name: Santa Clara
                    cod: 200
      operationId: get-kgfkg
      parameters:
        - schema:
            type: string
          in: query
          name: INN
        - schema:
            type: string
          in: query
          name: kpp
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                '':
                  type: string
components:
  schemas: {}
  securitySchemes: {}
