openapi: 3.0.0
info:
  title: OpenWeatherMap API
  version: '2.5'
  description: 'Get the current weather, daily forecast for 16 days, and a three-hour-interval forecast for 5 days for your city. Helpful stats, graphics, and this day in history charts are available for your reference. Interactive maps show precipitation, clouds, pressure, wind around your location stations. Data is available in JSON, XML, or HTML format. **Note**: This sample Swagger file covers the `current` endpoint only from the OpenWeatherMap API. <br/><br/> **Note**: All parameters are optional, but you must select at least one parameter. Calling the API by city ID (using the `id` parameter) will provide the most precise location results.'
  contact:
    name: Support
    url: 'https://openweathermap.org/api'
    email: some_email@gmail.com
  termsOfService: 'https://openweathermap.org/terms'
  license:
    name: CC Attribution-ShareAlike 4.0 (CC BY-SA 4.0)
    url: 'https://openweathermap.org/price'
servers:
  - url: 'http://localhohttps://api.openweathermap.org/data/2.5st:3000'
    description: prod
paths:
  /weather:
    get:
      summary: Your GET endpoint
      tags:
        - Weather endpoints
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                description: optional
                properties:
                  coord:
                    type: object
                    properties:
                      lon:
                        type: number
                        description: Геолокация города
                      lat:
                        type: number
                        description: Геолокация города
                  cod:
                    type: number
                    description: параметр
                  name:
                    type: string
                    description: Имя
                  id:
                    type: number
                    description: ID города
                  timezone:
                    type: number
                  sys:
                    type: object
                    properties:
                      type:
                        type: number
                      id:
                        type: number
                      country:
                        type: string
                      sunrise:
                        type: number
                      sunset:
                        type: number
                  dt:
                    type: number
                  clouds:
                    type: object
                    properties:
                      all:
                        type: number
                  wind:
                    type: object
                    properties:
                      speed:
                        type: number
                      deg:
                        type: number
                  visibility:
                    type: number
                  main:
                    type: object
                    properties:
                      temp:
                        type: number
                      feels_like:
                        type: number
                      temp_min:
                        type: number
                      temp_max:
                        type: number
                      pressure:
                        type: number
                      humidity:
                        type: number
                  base:
                    type: string
                  weather:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        main:
                          type: string
                        description:
                          type: string
                        icon:
                          type: string
              examples:
                example-1:
                  value:
                    coord:
                      lon: -121.95
                      lat: 37.35
                    weather:
                      - id: 803
                        main: Clouds
                        description: broken clouds
                        icon: 04n
                    base: stations
                    main:
                      temp: 45.25
                      feels_like: 41.16
                      temp_min: 41
                      temp_max: 50
                      pressure: 1026
                      humidity: 75
                    visibility: 16093
                    wind:
                      speed: 2.57
                      deg: 36
                    clouds:
                      all: 75
                    dt: 1579415808
                    sys:
                      type: 1
                      id: 5845
                      country: US
                      sunrise: 1579360793
                      sunset: 1579396557
                    timezone: -28800
                    id: 0
                    name: Santa Clara
                    cod: 200
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  '':
                    $ref: '#/components/schemas/unauthorized_response'
              examples: {}
      operationId: get-weather
      parameters:
        - schema:
            type: string
          in: query
          name: zip
          description: '**Zip code**.Search by zip code.'
      security:
        - app_id: []
components:
  schemas:
    unauthorized_response:
      title: 401
      type: object
      description: ''
      properties:
        code:
          type: integer
        message:
          type: string
      required:
        - code
        - message
  securitySchemes:
    app_id:
      name: appid
      type: apiKey
      in: query
tags:
  - name: Weather endpoints
